CREATE DATABASE IF NOT EXISTS DATA;
CREATE TABLE IF NOT EXISTS DATA.SENSOR_DATA( 
	ID INT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    DEV_EUI VARCHAR(20) NOT NULL,
    LATITUDE DECIMAL(11,7) NOT NULL,
    LONGITUDE DECIMAL(11,7) NOT NULL,
    LOCATION VARCHAR(30) NOT NULL,
    PUBLISH_TIME timestamp NOT NULL DEFAULT current_timestamp(),
    TEMP DECIMAL (3,1) NOT NULL
    );
    
-- Test 
INSERT INTO DATA.SENSOR_DATA (DEV_EUI, LATITUDE, LONGITUDE, LOCATION, TEMP) VALUES ("6081F9D1BAF7C83C", 51.17871291510539, 4.57810418773288, "Broechem", 26); 
SELECT * FROM DATA.SENSOR_DATA;

